name = "TcpInstruments"
uuid = "aaee30c5-7b57-4441-b61a-ab7186f11903"
authors = ["Morten F. Rasmussen <10264458+mofii@users.noreply.github.com>, Steve Leung <steve@orchardultrasound.com>, and Esti Gajda"]
version = "0.8.6"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
InstrumentConfig = "2ae464b0-21de-4247-9233-e7c17725eb53"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
InstrumentConfig = "0.2"
JLD2 = "0.4"
MAT = "0.10"
RecipesBase = "1.1"
TestSetExtensions = "2.0"
Unitful = "1"
YAML = "0.4"
julia = "1"
OffsetArrays = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
